### ISSUE TITLE
Problem after installing 2.1.0

### ISSUE THREAD

**Issue by sveins12** [faresamr/AspNetCore.Identity.Stores#16]
I had a problem after going from 2.0.0 to 2.1.0. 

For some unknown reason the whole application crashes during initialization of services that use classes like UserManager<T>.

I tried to place try/catch around the creation of service UserManager<T>, but no error was catched. The app just went straight down. It is a Blazor server application using .net 6.

The only uncommon I saw in the log was this:

> DocDBTrace Information: 0 : Azure Environment metadata information not available. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

My solution was to roll back to 2.0.0.

**Comment by faresamr** [comment]
Thank you @sveins12 for addressing this.

Can you please provide more details about your setup
- which package you are using? (For CosmosDb or StorageAccount)
- if possible to share a code snippet  from program.cs where you initialize the identity stores.

The only difference between 2.0.0 and 2.1.0 is additional overloads to creat the connection client with preserving the original overlord for backwards compatibility.

**Comment by sveins12** [comment]
I use `Microsoft.Azure.Cosmos 3.31.0`

The initialization:
```c#
services.Configure<IdentityStoresOptions>(options => 
     options.UseAzureCosmosDB(connectionString, databaseId: database));
```

Today, using the same code from a webassembly server (server side) , I got an exception which may help:
> System.MissingMethodException: Method not found: 'AspNetCore.Identity.Stores.IdentityStoresOptions AspNetCore.Identity.Stores.AzureCosmosDB.Extensions.IdentityStoresOptionsExtensions.UseAzureCosmosDB(AspNetCore.Identity.Stores.IdentityStoresOptions, System.String, System.String, System.String)'.

It's almost like something is missing from the Options class/object?

**Comment by faresamr** [comment]
Usually, `System.MissingMethodException` caused by assembly not being copied properly to the output folder it happens from time to time.
Can you please upgrade to v2.1.0 and then [clean and rebuild](https://learn.microsoft.com/en-us/visualstudio/ide/building-and-cleaning-projects-and-solutions-in-visual-studio?view=vs-2022#to-build-rebuild-or-clean-an-entire-solution) your solution? if it didn't solve the problem try to delete the debug folder manually then rebuild

I tried to reproduce this issue on Blazer server project with all possible scenarios came up to my mind based on the provided info about your environment, but everything worked fine.
Can you please give it a try and let me know whether if it solves your issue.

**Comment by sveins12** [comment]
Hi again. I finally got time to test that, but it doesn't seem to work for me. 

I updated the to v2.1.0 and cleaned and rebuilded. I also tried removing the .vs folder. 

I can see this in the log, but I don't know if it could be any help or if it is related:

> info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[7] Identity.Application was not authenticated. Failure message: Unprotect ticket failed

**Comment by sveins12** [comment]
Hi, @faresamr 

I have been using v2.0.0 all the time, because of the crash. But now I decided to give v2.1.0 a new try.

In .net 8 it just hangs instead of crashing/quitting the app. 

I found that it happens at IdentityStoresOptionsExtensions.cs at line 34:

```C#
var createDatabaseResponse = await azureCosmosDBOptions.CosmosClient.CreateDatabaseIfNotExistsAsync(azureCosmosDBOptions.DatabaseId);
```

### Something strange:
I commented out the database creation and container creation code and it was working. The strange thing is that after doing that, I could put the code back in, and then it worked. Until the next day. Very strange. 

I traced through the CosmosClient `CreateDatabaseIfNotExistsAsync` code and everything went fine until it was returning. Then, inside the code that handles the await/task stuff, it just hangs. So it is never returning.

**Comment by faresamr** [comment]
Hi @sveins12 
sorry for the late response and thank you reaching out and find this issue.

The root cause of this problem is that I'm trying to call Async method within synchronously while registering the Cosmos DB in [IdentityStoresOptionsExtensions.cs](https://github.com/faresamr/AspNetCore.Identity.Stores/blob/main/AspNetCore.Identity.Stores/AspNetCore.Identity.Stores.AzureCosmosDB/Extensions/IdentityStoresOptionsExtensions.cs#L27)

```
InitializeDatabaseAsync(azureCosmosDBOptions).GetAwaiter().GetResult();
``` 

I will be migrating the library to .Net8 as we have to update the dependencies, also I will fix this issue as well using this item #17

**Comment by faresamr** [comment]
Hi @sveins12 
V3.0.0 has been released and ready to be used.
However, to fix the issue of Async Anti-Pattern the library will not create the database and container if they are not existed unless you are using [UseIdentitySeedingAsync](https://github.com/faresamr/AspNetCore.Identity.Stores/blob/main/AspNetCore.Identity.Stores/SampleWebApplication/Program.cs#L63-L72) otherwise, the CosmosDb has to be ready with the container created.

Please feel free to open a new issue if something came up.

**Comment by sveins12** [comment]
Fantastic, I will try it.

**Comment by sveins12** [comment]
Finally had the time to try it now, and the new version is working!
